apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedksqls.mgazza.github.com
spec:
  group: mgazza.github.com
  names:
    kind: ManagedKSQL
    plural: managedksqls
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            statement:
              type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
