apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ksql-operator
  template:
    metadata:
      labels:
        name: ksql-operator
    spec:
      serviceAccountName: ksql-operator-service-account
      containers:
        - name: ksql-operator
          image: ghcr.io/mgazza/ksql_operator:latest