
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ksql-operator
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ksql-operator
subjects:
  - name: ksql-operator-service-account
    namespace: default
    kind: ServiceAccount
