/*
 * KSQL
 *
 * This is a swagger spec for ksqldb
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Statement struct {
	Ksql              string                      `json:"ksql,omitempty"`
	StreamsProperties *StatementStreamsProperties `json:"streamsProperties,omitempty"`
}
