/*
 * KSQL
 *
 * This is a swagger spec for ksqldb
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StatementStreamsProperties struct {
	KsqlStreamsAutoOffsetReset string `json:"ksql.streams.auto.offset.reset,omitempty"`
}
