/*
 * KSQL
 *
 * This is a swagger spec for ksqldb
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Format string

// List of format
const (
	JSON_Format      Format = "JSON"
	AVRO_Format      Format = "AVRO"
	PROTOBUF_Format  Format = "PROTOBUF"
	DELIMITED_Format Format = "DELIMITED"
)
