/*
 * KSQL
 *
 * This is a swagger spec for ksqldb
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShowListResponseQueries struct {
	QueryString string `json:"queryString,omitempty"`
	Sinks       string `json:"sinks,omitempty"`
	Id          string `json:"id,omitempty"`
}
