/*
 * KSQL
 *
 * This is a swagger spec for ksqldb
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateDropTerminateResponseCommandStatus struct {
	Status  string `json:"status,omitempty"`
	Message string `json:"message,omitempty"`
	QueryId string `json:"queryId,omitempty"`
}
